# Generated by Django 5.1.1 on 2025-02-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usersettings_id_usersettings_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='user_id',
            new_name='user',
        ),
    ]
