# Generated by Django 5.1.1 on 2025-02-21 03:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
