# Generated by Django 5.1.1 on 2025-02-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_end_date_alter_tasks_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
