# Generated by Django 5.1.1 on 2025-02-21 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_modified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagsuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='user_id',
            new_name='user',
        ),
    ]
