# Generated by Django 5.1.1 on 2025-02-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tagsuser_name_tagsuser_unique_tag_per_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='creates_at',
            new_name='created_at',
        ),
    ]
