# Generated by Django 5.1.1 on 2025-02-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_tasks_priority_alter_tasks_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
