# Generated by Django 5.1.1 on 2025-02-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_rename_priority_tasks_prior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='task',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='prior',
            new_name='priority',
        ),
    ]
