# Generated by Django 5.1.1 on 2025-02-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_task_comments_task_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
    ]
